apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: master1.ceyes.os
    path: /home/data/jenkins
